// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvbmcmoznynjllaiyujd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2Ym1jbW96bnluamxsYWl5dWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDI3MjQsImV4cCI6MjA2ODE3ODcyNH0.2O3kEsQmnexsvSPMmOxNeLIZID0YDSpjssJ9i5M-7PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});